export const DAYBOOK_COPY = {
  overline: 'Day-book',
  reconHeading: 'Reconciliation',
  postAllBalanced: 'Post all balanced',
  prevDay: 'Previous',
  nextDay: 'Next',
  litres: 'Litres',
  expected: 'Expected',
  declared: 'Declared',
  variance: 'Variance',
  attendant: 'Attendant · pump',
  shiftTotal: 'Day total',
  emptyTitle: 'Nothing recorded yet.',
  emptyBody: 'Open a shift or record the opening dip to start the day.',
  tanksHeading: 'Tank dips',
  postedAllMark: '✓ POSTED',
  postedAllMessage: (n: number) => `${n} balanced shift(s) posted.`,
} as const;

export const SHIFT_COPY = {
  overline: 'Shift',
  meterTrail: 'Meter trail',
  cashTrail: 'Cash trail',
  opening: 'Opening',
  closing: 'Closing',
  dispensed: 'Dispensed',
  expectedGross: 'Expected gross',
  cashDeclared: 'Cash declared',
  variance: 'Variance',
  closePump: 'Close pump',
  closingMeterLabel: 'Closing meter',
  cashDeclaredLabel: 'Cash declared (₦)',
  post: 'Post shift',
  voidShift: 'Void shift',
  closedMark: '✓ PUMP CLOSED',
  postedMark: '✓ SHIFT POSTED',
  voidedMark: '✓ SHIFT VOIDED',
  voidTitle: 'Void this posted shift?',
  voidBody:
    'This reverses a posted shift. It stays visible in the day-book — struck through — and is recorded in the audit log permanently.',
} as const;
