export const STAFF_COPY = {
  overline: 'Staff',
  title: 'The people on the forecourt.',
  add: 'Add staff',
  emptyTitle: 'No staff yet.',
  emptyBody: 'Add a manager or attendant to this branch.',
  role: 'Role',
  shifts30d: '30-day shifts',
  variance30d: '30-day variance',
  leaderboardHeading: 'Variance leaderboard · 30 days',
  addedMark: '✓ STAFF ADDED',
  nameLabel: 'Full name',
  emailLabel: 'Email',
  phoneLabel: 'Phone',
  passwordLabel: 'Temporary password',
  save: 'Add staff',
} as const;

export const STAFF_DETAIL_COPY = {
  overline: 'Staff member',
  branchesHeading: 'Branches & roles',
  metricsHeading: 'Track record',
  shiftsHeading: 'Recent shifts',
  activityHeading: 'Activity',
  noActivity: 'No activity recorded yet.',
  noShifts: 'No shifts yet.',
  totalShifts: 'Total shifts',
  shifts30d: '30-day shifts',
  variance30d: '30-day variance',
  changeRole: 'Change role',
  deactivate: 'Deactivate',
  reactivate: 'Reactivate',
  assignBranch: 'Assign to branch',
  resetPassword: 'Reset password',
  editAccount: 'Edit account',
  changeRoleTitle: 'Change role',
  changeRoleSave: 'Save role',
  roleChangedMark: '✓ ROLE CHANGED',
  deactivateTitle: 'Deactivate this member?',
  deactivateBody: 'They keep their history but can no longer sign in or be assigned shifts.',
  deactivatedMark: '✓ DEACTIVATED',
  reactivatedMark: '✓ REACTIVATED',
  assignTitle: 'Assign to another branch',
  assignBranchLabel: 'Branch',
  assignRoleLabel: 'Role at that branch',
  assignSave: 'Assign',
  assignedMark: '✓ ASSIGNED',
  resetTitle: 'Reset this password?',
  resetBody: 'A new temporary password is generated. Hand it over securely; they reset it on next sign-in.',
  resetMark: '✓ PASSWORD RESET',
  tempPasswordLabel: 'Temporary password',
  editTitle: 'Edit account',
  editNameLabel: 'Full name',
  editEmailLabel: 'Email',
  editPhoneLabel: 'Phone (optional)',
  editSave: 'Save changes',
  editedMark: '✓ ACCOUNT UPDATED',
} as const;

export const ROSTER_COPY = {
  overline: 'Roster',
  title: 'This week’s shifts.',
  weekOf: 'Week of',
  save: 'Save roster',
  savedMark: '✓ ROSTER SAVED',
  days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
} as const;

export const ROLES_COPY = {
  overline: 'Roles & permissions',
  title: 'Who can do what.',
  newRole: 'New role',
  systemRole: 'System',
  permissionsHeading: 'Permissions',
  nameLabel: 'Role name',
  save: 'Save role',
  savedMark: '✓ ROLE SAVED',
  deletedMark: '✓ ROLE DELETED',
  deleteTitle: 'Delete this role?',
  deleteBody: 'Staff assigned to this role must be reassigned first.',
} as const;
