import { randomBytes } from 'node:crypto';

import { ulid } from 'ulid';

// Sufficient for request IDs and idempotency keys. Not for tokens.
export const newRawId = (): string => randomBytes(12).toString('hex');

// Resource-prefixed ULIDs are the application identity used as the document `_id`. They
// are the single biggest DB-portability lever: identity is generated by us, not by Mongo's
// ObjectId, so it carries unchanged to MySQL/Postgres. ULIDs are URL-safe and sortable.
export const ID_PREFIX = {
  org: 'org',
  user: 'usr',
  membership: 'mbr',
  role: 'rol',
  branch: 'brn',
  tank: 'tnk',
  pump: 'pmp',
  shift: 'shf',
  dip: 'dip',
  delivery: 'dlv',
  price: 'prc',
  expense: 'exp',
  note: 'not',
  notification: 'ntf',
  audit: 'aud',
  roster: 'rst',
  otp: 'otp',
  session: 'ses',
} as const;

export type ResourceKind = keyof typeof ID_PREFIX;

export const newId = (kind: ResourceKind): string => `${ID_PREFIX[kind]}_${ulid()}`;
